controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ['base_left_wheel_joint']
    right_wheel_names: ['base_right_wheel_joint']
    wheel_separation: 0.277
    wheel_radius: 0.03
