controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


diff_drive_controller:
  ros__parameters:
    use_stamped_vel: false
    publish_rate: 100.0
    enable_odom_tf: true

    base_frame_id: base_footprint
    odom_frame_id: odom

    left_wheel_names: ['base_left_wheel_joint']
    right_wheel_names: ['base_right_wheel_joint']
    wheel_separation: 0.258
    wheel_radius: 0.0325

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]